name: Run integration tests 2 for any chain (peg)
on:
  push:
    paths-ignore:
      - "ui/**"

jobs:
  test:
    timeout-minutes: 40
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: Sifchain/sifchain-devops
          path: deploy
          token: "${{ secrets.GIT_PAT }}"

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - run: |
          echo $GOBIN
          echo $GOROOT
          which go


      - name: Use Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'


      - name: Set up linux environment
        run: # installs development tools and updates .bash_profile
          bash test/integration/setup-linux-environment.sh
      - name: Setup integration test environment
        run: |
          source $HOME/.bash_profile
          git clean -fdx
          cd smart-contracts && make clean && make && make tests

      # - name: Execute test chain integration tests
      #   run: |
      #     source $HOME/.bash_profile
      #     . test/integration/vagrantenv.sh
      #     export LOG_LEVEL=DEBUG
      #     bash test/integration/execute_integration_tests_against_any_chain.sh
      # - name: Archive logs from test
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: testlogs2
      #     path: test/integration
