name: Smart Contracts

on: ['push']

  # pull_request:
  #   paths: ['smart-contracts/**']

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smart-contracts

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'
      - name: Clean dependencies
        run: make clean

      - name: Install dependencies
        run: make install

      - name: Test Setup
        run: make tests
